---
- name: A simple play to test ansible.cfg
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:

  # the command module issues a command on the remote host
  - name: Issue a date cmd on each remote host
    command: date

